name: Convert and Notify

on:
  push:
    branches:
      - main

jobs:
  process-tga:
    environment: Convert and Notify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.3.0"

      - name: Install dependencies
        run: npm install discord.js glob

      - name: Debug environment variables
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: echo "DISCORD_TOKEN is set to: ${DISCORD_TOKEN:0:4}****"

      - name: Find and process .tga files
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: node ./convert-and-notify.js
