name: Convert and Notify

on:
  push:
    branches:
      - main
      - add-notify-job

jobs:
  process-tga:
    runs-on: ubuntu-latest
    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23.3.0"

      - name: Install dependencies
        run: npm install discord.js glob

      - name: Find and process .tga files
        run: node ./convert-and-notify.js
